apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP_NAME 
  namespace: default 
spec:
  selector:
    matchLabels:
      app: APP_NAME
  replicas: 1
  template:
    metadata:
      labels:
        app: APP_NAME
    spec:
      containers:
      - image: DOCKER_IMAGE_TAG 
        imagePullPolicy: Always
        name: APP_NAME
        ports:
        - containerPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: APP_NAME
  namespace: default 
  annotations:
    alb.ingress.kubernetes.io/group.name: default-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:872521300165:certificate/c8d829d1-803e-4438-a2d6-f0d6ff73d350
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]' # enable ssl
    alb.ingress.kubernetes.io/ssl-redirect: '443'

spec:
  ingressClassName: alb
  rules:
    - host: APP_NAME.tinylab.ml
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: APP_NAME
                port:
                  number: 80
